[font]
size = 11.0


[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "SemiBold"


[colors.primary]
background = "0x020221"
foreground = "0xb4b4b9"

[colors.cursor]
text = "0x020221"
cursor = "0xffe8c0"

[colors.normal]
black = "0x000004"
red = "0xff3600"
green = "0x859933"
yellow = "0xffc552"
blue = "0x635196"
magenta = "0xff761a"
cyan = "0x34bfa4"
white = "0xb4b4b9"

[colors.bright]
black = "0x020221"
red = "0xff8e78"
green = "0xb2bc55"
yellow = "0xffd392"
blue = "0x99a4bc"
magenta = "0xffb07b"
cyan = "0x8bccbf"
white = "0xf8f8ff"

[window]
dynamic_padding = false
decorations = "full"
# startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 20
y = 20
